version: "3"
services:
  dev:
    build:
      context: devcontainer
      args:
        NODE_VERSION: lts/*
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 9000:8080
    volumes:
      - ./swagger:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml

  swagger_editor:
    image: swaggerapi/swagger-editor
    ports:
      - 9001:8080
